[package]
edition = "2024"
name = "lr_format_sol"
version = "0.1.0"

[dependencies]
amf0 = {path = "../amf0"}
lr_types = {path = "../lr_types"}
quick_byte = {path = "../quick_byte"}
thiserror = "2"
vector2d = {path = "../vector2d"}

[dev-dependencies]
pretty_assertions = "1"
